In [2]:
# Numpy :help to work with arrays (homogenmious) multidimension array

In [3]:
import numpy as np

In [4]:
lst=[1,2,3,4]
arr=np.array(lst)

List = collection of non homogineous element

array = collection of homogineous element

In [5]:
  arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(4,)

In [8]:
arr1=np.array([[1,2,3],[4,5,6]])

In [9]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 2D array
arr1.shape

(2, 3)

In [11]:
#3D array
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
ar.shape

(3, 3)

In [13]:
arr1.dtype

dtype('int32')

In [14]:
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#skiping
np.arange(1,10,2)#2 is skiping size will take two steps

array([1, 3, 5, 7, 9])

In [16]:
    np.array((1,2,3,4))

array([1, 2, 3, 4])

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr1.dtype

dtype('int32')

In [19]:
np.arange(1,10) #1 to less than 10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(1,10,2) #2 is step size (it will skip every 2nd element)

array([1, 3, 5, 7, 9])

In [21]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [22]:
a1=np.arange(1,20,2)

In [23]:
np.shape(a1)

(10,)

In [24]:
a1=np.arange(1,20,2).reshape(2,5) #reshaping to 2 rows and 5 column

In [25]:
a1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [26]:
a1.shape

(2, 5)

In [27]:
a1.dtype

dtype('int32')

In [28]:
a2=np.arange(50,1,-2) #min and max it should start with 50 and end at 1
# give step size in minuse then it will show it in reverce

In [29]:
a2

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [30]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a3=np.linspace(1,20,40) #linspace (linearly spaced)

In [32]:
a3

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [33]:
a3.shape

(40,)

In [34]:
a3.reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
np.ones((5,2,8)) #5 arrays of 2 rows and 5 column 

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [39]:
5 + np.ones((3,5)) #brodcasting operation

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [40]:
#indentity matrix ( diagonal are one)
np.eye(6).reshape(4,9) #can put any number 
#just those can be multi to total number 

array([[1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [41]:
print("Rndom number generation(uniform distribution)")
np.random.rand(2,3)

Rndom number generation(uniform distribution)


array([[0.18691641, 0.35038193, 0.03650856],
       [0.90772609, 0.35292717, 0.32020291]])

In [42]:
print("random number following a normal distribution with mean=0 and std=1")
print(np.random.randn(5,3))

random number following a normal distribution with mean=0 and std=1
[[ 0.02573685 -0.41549199  0.20276931]
 [ 0.90836061 -1.13012648  0.35707138]
 [-2.01044148 -0.16837574 -0.5882467 ]
 [-0.85846836 -1.04261343  0.5546016 ]
 [ 0.59693293  0.47487263 -1.83371034]]


In [43]:
np.random.randint(1,100,5)

array([48, 45, 62, 93,  8])

In [44]:
np.random.randint(1,100,(4,4))

array([[65, 56,  1, 22],
       [35, 82, 14, 35],
       [59, 92,  9, 97],
       [60, 45, 62, 90]])

In [45]:
arr=np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[2:] #slicing 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [49]:
arr[-1:7:-1]

array([10,  9,  8])

In [50]:
#2d array
arr1=np.random.randint(2,100,20).reshape(5,4)

In [51]:
arr1

array([[35, 30, 11, 81],
       [28, 52, 65, 56],
       [71, 36, 55,  6],
       [56,  6, 27, 58],
       [20, 12, 90, 20]])

In [52]:
arr1[0:3]

array([[35, 30, 11, 81],
       [28, 52, 65, 56],
       [71, 36, 55,  6]])

In [53]:
arr1[0:3,0:3]

array([[35, 30, 11],
       [28, 52, 65],
       [71, 36, 55]])

In [54]:
arr1[2:4,1:4]

array([[36, 55,  6],
       [ 6, 27, 58]])

universal function

In [55]:
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [56]:
arr1

array([[21,  2, 21],
       [66, 49, 31],
       [86, 42, 79]])

In [57]:
arr2

array([[61, 93, 38],
       [92, 26, 21],
       [68, 50, 70]])

In [58]:
arr1 * arr2 #any operation can do shape should be same Ex- 3*3

array([[1281,  186,  798],
       [6072, 1274,  651],
       [5848, 2100, 5530]])

In [59]:
np.sqrt(arr1)

array([[4.58257569, 1.41421356, 4.58257569],
       [8.1240384 , 7.        , 5.56776436],
       [9.2736185 , 6.4807407 , 8.88819442]])

In [60]:
np.exp(arr2)

array([[3.10429794e+26, 2.45124554e+40, 3.18559318e+16],
       [9.01762841e+39, 1.95729609e+11, 1.31881573e+09],
       [3.40427605e+29, 5.18470553e+21, 2.51543867e+30]])

In [61]:
np.log10(arr1)

array([[1.32221929, 0.30103   , 1.32221929],
       [1.81954394, 1.69019608, 1.49136169],
       [1.93449845, 1.62324929, 1.89762709]])

In [62]:
arr1=np.arange(1,10)

In [63]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr1[2:]=1000 #brodcasting

In [65]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [66]:
np.dot(arr,arr)

385

In [67]:
np.linspace(1,20,40).reshape(20,2) #linear equal spaced

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [68]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [69]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [71]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [73]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### creating random values using numpy

In [80]:
print("Random number from uniform distribution")
np.random.rand(2,3)

Random number from uniform distribution


array([[0.0890871 , 0.27926224, 0.49693202],
       [0.7587189 , 0.63433408, 0.2979286 ]])

In [83]:
 print("random number following normal distribution with mean=0 and std=0")
 print(np.random.randn(5,3))


random number following normal distribution with mean=0 and std=0
[[-0.5879211   1.18428927  0.98692703]
 [ 0.31673479  0.26307774  1.25366006]
 [-0.974424    1.22609874 -0.15286023]
 [ 1.00366359  0.48502568  1.32381601]
 [-1.28996009  0.26628971 -0.9233404 ]]


In [87]:
#it is method which gives number between that number min to max is given (1,100,10) one and 100 is limit and 10 is number of random number is requitred 
np.random.randint(1,100,10)

array([95, 76, 36, 71, 89, 37, 92, 36, 15, 91])